apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: paulynomial-index
  annotations:
    field.cattle.io/description: Splash page for personal site
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: null
  paths:
    - /kube
  repo: https://github.com/paulkiernan/paulynomial-index
  targets:
    - clusterSelector:
        matchLabels:
          management.cattle.io/cluster-name: c-gzcnw
type: fleet.cattle.io.gitrepo
