apiVersion: ENC[AES256_GCM,data:Rl0=,iv:HrXhYq+hvrWuMDxVSqtdedO59sqjvZgMe4mqRJ2KeD0=,tag:yz/EasijhD4TVmdm2IACkQ==,type:str]
kind: ENC[AES256_GCM,data:BLcYmfhP,iv:ZcMViqWAAbM0elYy+Eb+t41EQVxdZPN86EinEEl40sg=,tag:gYSujzl6/1P+9XhIiAv+Mg==,type:str]
clusters:
-   name: ENC[AES256_GCM,data:BDyy79m8kCnXoA==,iv:LVM+EyUwMtzpD5m9tcn96oBkgad8GNfbIyZ4jizMxs8=,tag:S3PzSAXZQlR11gZK1ejflw==,type:str]
    cluster:
        server: ENC[AES256_GCM,data:gsc0sFuHxi+LBaVuq/QdFf4ss4JyQinruxWGFXnWd+iNY5U6u2QiEvCrPR1A44OPw/raSQ==,iv:9XBfBzmT5bTEkKo1l1aCTIcDjdwys5A3stGS89wl4y4=,tag:z6AgoK/uocNR24/nPFAPvA==,type:str]
        certificate-authority-data: ENC[AES256_GCM,data:wuiaDC2xuyWm/6UmdU20RSnGtWwwCWsGTVVQ+YlER44UwwVR5z+Euhzvi4ZQ6Wz3Kfby1/3DWnV9zcNbe1aHCO4AP5HEQkAlCE1FwTsI7URCCdh006goTo2ZAgCGdJQIKOIcywDQ62Eh4GNZfLzHviYi+aGGd3CmkBhgY5H4tVAbvLiAL4esVfanM2tWWfJnopBqJ2QNluuvofdv6NV27Z7tdqZVYOyhPyMooJv7pVkomhgULASTb+z6qQmUXcF4O30j4StZNkSYl13lj+EYg6MKgX8sj2bJlWRYYBqTE/JrDpg5ip+3JSmVoZHRXZBHX9NxCZuO/SyhjwEG2PUUBOTnn2UQD9s2OPcUytKc2yQjd77NEDVYfaCQOwilm9jtILZh2bqSxTKXs5QOqJzhlViOhmp7kEHH9n0Bzh6rQref9f3xTH+TdZcG0XyIPTLBfMJhejz6k2o7AjNZ5Ds2ns+mLWzPLop2nYKHvC/bq8s8RAzbTIzxpQx15dXmjfZzqKkOkNpTnJnzYMflXF+xPLOn92J3Qga0fDZvOnwq5DLFlO5WQOYKg551fmuKt4G33jJo5BKUvcKcYy7OnfTZR8rilFlT+SFNwMWugdhkziUkN6H7LwU9dPPqNE+7jeJdOL4sdQrLted55i2Gbjo58l9IXh1swu8bKbpC07ck7O4aQkkEHniQSGSZCSA8SFP8kWdGWVnbnd7DRRuluGHRzI8zOQGoG/qwzWdy0fu59VmUFWdBEJy139oF7xc171jsucINEwxN3Siuuw0WmK5vjR4Aq8CwdGMnOJmp9Wx9zrDxYRXck8IOKU/ahugzfZeyYjymM5pOf/WQF9sCL9hdcRx5ezjiA/6uOJTUNBM67Ns55gY0GBZQj4s6RxhMoANfbkzrN4FhbFLMmcrDsPUIn8yso/An8xSVDmbtH00nroMYEFGOENHZCwyXoWDTVf9Pr0pR5VirtrSKk6tK1GpuAEauGWsPLhWB9mExUSFfaixOgvmPPcMK+D4PvafvdBml/gz6uEtDqXGbK6iBI9GBYF7WRj8=,iv:7KzGH6CTgOj0v+HPxw6uGw+YQucIDOExdUVqWjlLx70=,tag:xQGdYqCUiO2MczYAYpqByw==,type:str]
users:
-   name: ENC[AES256_GCM,data:B17WAEqgdetBnQ==,iv:02be4EYx2kkryUyyZZj7yXdJuU1Kfy3YGdaBLl1TYq0=,tag:y2Un2AhJLIn/tMT/AK/6tA==,type:str]
    user:
        token: ENC[AES256_GCM,data:tpmCAFOSJ34eg4gJisA9g7vGHbIxjECe1pfcTAUndc0CdlG3cBg74n+jW8zlKZGbqZbT9GluqwJb7rvQeBm/5sJbaRfogwCZcLcliQ==,iv:4pCB3tMqB6FuhgwIitgtYLTLqObyUC12QJ/8CKwIPW0=,tag:NK4D+je0wLcD0N6ijZQzYQ==,type:str]
contexts:
-   name: ENC[AES256_GCM,data:xZxpDB8T4YW6Ww==,iv:gz9+qaF+lKVkIGxmgSYDNkPgLoftyROy9syXUS1tpw8=,tag:/2XObop8F4XtSQLpuM/VHQ==,type:str]
    context:
        user: ENC[AES256_GCM,data:Xy6O/ltnZLqCEg==,iv:3o4HsYYI8lPlzwFktxbig69wdPHkd88qv0O8kF/b7Bg=,tag:YS0zwxuLv5czlpUb8c0UmA==,type:str]
        cluster: ENC[AES256_GCM,data:a1sLcT8JcztedA==,iv:J24mUG9zDb2pxrN039afp2HnOBAsO9J6IBfmQ/WxrTQ=,tag:3dK41lvpi61TXFX99Rw/5A==,type:str]
current-context: ENC[AES256_GCM,data:ouDKq7I+d7SbdQ==,iv:Cw00gvJxwHqSLBPxIe8Z/0cz4wvCBKxkZGBKVZaqxyQ=,tag:xiy9Q7+MWy3MtCda8P9JVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-17T07:13:27Z'
    mac: ENC[AES256_GCM,data:NX7rhVESWnxqOXLJq5iH4PYwDMNpYrg0pDeBtwA89HFyz9ymE2OY0pSeljl0VUyHV8r9liPTjpqzC/iVxe95SkGFkyZNZUczkDWA1q/wMq91oM0BnjSOpSr2UUlXr6YWlX37raxafodUxomitpmT20JLPJ9ZXWWbdnZ/CUVMzBg=,iv:WswLDfff8ZFmA53dXLxfLJcBptcuM0nfscuGaVcq8pA=,tag:iKTVLAF9EeFbVKWcYumn+A==,type:str]
    pgp:
    -   created_at: '2020-12-17T07:13:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/pkH+tfoZrvAQgApzK3IAQZjPRDLvtqJSbyzdry+FvRUSq263pGRO1hg10P
            To+Jum8uQtq7TNsPITc4Q7+/QNd8kI060HaetcXZNA5LQU3RNEZ9EMzIiHUUwnyr
            EDB5BL5aOPm21FQZhfzuk5ksSRgCkCZ7gxvNYzTyScjPDmS7oGHmaTQDIKPhYl0P
            n0mJY4eVui+jOYGsTSk4GVWFzu61LdMmDDJJMbSYWXoKT+j9Jyl94lUwL3Qx8Th1
            mf06U/B2LRYH+GWYzkgcjjc/Wz1WRXulCr6pt+uxomQQLRIYhOjloPklzPMkrmCi
            O9w+H3L1Er1l2j0ISgbCHjDoyWKPZTd+2tJtlvFYTdJcAS/pjvBrHlnNLgBV7bk3
            CxWtZcdc+insEQloYay3dV/4NOtJ6bHyM9Lq1R/xb2rTbK/uiD+RXGkL34s9IZhl
            RImqlX9q6HWutQwQJ8tjxd0mfDWda4lGGbruSI4=
            =5Ca6
            -----END PGP MESSAGE-----
        fp: 68C23980CD8ECC0DA9F95ECF9AFAE26394816684
    unencrypted_suffix: _unencrypted
    version: 3.6.1
